/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package newproj;

public class App {
    public static int sum(int i, int j) {
        return i+j;
    }

    public static void main(String[] args) {
        System.out.println(sum(5,5));
        System.out.println("blabla");
    }
}
