/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package newproj;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void sumNotnull() {
        assertNotNull(App.sum(5,5), "app should give back a number.");
        
    }
    @Test void sumGivesValidNumber(){
        assertEquals(10, App.sum(5,5));
    }
}
